### ISSUE TITLE
ES query error

### ISSUE THREAD

**Issue by inutano** [inutano/cwl-metrics-client#4]
The `bucket_size_query` fails with the error like below:

```
Traceback (most recent call last):
	8: from /cwl-metrics-client/lib/client.rb:17:in `<main>'
	7: from /cwl-metrics-client/lib/cwl-metrics/cwl-metrics.rb:18:in `json'
	6: from /cwl-metrics-client/lib/cwl-metrics/cwl-metrics.rb:103:in `metrics'
	5: from /cwl-metrics-client/lib/cwl-metrics/cwl-metrics.rb:117:in `fetch_metrics'
	4: from /usr/local/bundle/gems/elasticsearch-api-6.0.2/lib/elasticsearch/api/actions/search.rb:187:in `search'
	3: from /usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/client.rb:131:in `perform_request'
	2: from /usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	1: from /usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/base.rb:323:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] failed to parse field [size]","line":1,"col":315}],"type":"parsing_exception","reason":"[terms] failed to parse field [size]","line":1,"col":315,"caused_by":{"type":"illegal_argument_exception","reason":"[size] must be greater than 0. Found [0] in [summary_per_container_id]"}},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
```

Any idea for this? @tom-tan

**Comment by inutano** [comment]
The error occurs when I hit `cwl-metrics fetch` command right after the execution of workflows: the error message indicates that there're no record in the Elasticsearch. After a while, the error message is gone, so it should be because the data record is being processed and not recorded.
